#HBPOP2022 SNPGenie Prep
#' organizes dataframes used for genetic diversity analysis
#' @param snp_gen_out data.frame generated by SNPGenie 
#' @param popnames text file with sample names in column 1 and population categories in columns 2:#
#' @returns data.frame of merged datasets
#' @importFrom dplyr coalesce
#' @examples set later 
#' @export

hbpop_snpdf <- function(snp_gen_out, popnames) {
  snp_gen_out <- subset(snp_gen_out, select=-c(1))
  snp_gen_out$product <- gsub('rna-', '', snp_gen_out$product)
  snp_gen_out$NS <- snp_gen_out$piN/snp_gen_out$piS
  snp_gen_out <- na.omit(snp_gen_out)
  snp_gen_out <- snp_gen_out[!is.infinite(snp_gen_out$NS),]

  data(gb_ncbi)
  data(gb_gbo)
  gb_gbo$comb <- gb_gbo$GBold %?% gb_gbo$GB
  gb_ncbi_comb <- merge(gb_gbo, gb_ncbi, by.x="comb", by.y="transcript", all.y=TRUE)
  gb_ncbi_comb <- select(gb_ncbi_comb, -GBold)
  gb_ncbi_fin <- gb_ncbi_comb[!(gb_ncbi_comb$comb==""),]

  merge(popnames, merge(gb_ncbi_fin, snp_gen_out, by.x="transcript", by.y="product"))
}