#HBPOP2022 SNPGenie Prep
#' organizes dataframes used for genetic diversity analysis
#' @param snp_gen_out data.frame generated by SNPGenie 
#' @param popnames text file with sample names in column 1 and population categories in columns 2:#
#' @return data.frame of merged datasets
#' @import dplyr
#' @examples tbd
#' @export

hbpop_snpdf <- function(snp_gen_out, popnames) {
  snp_gen_out <- subset(snp_gen_out, select=-c(1))
  snp_gen_out$product <- gsub('rna-', '', snp_gen_out$product)
  snp_gen_out$NS <- snp_gen_out$piN/snp_gen_out$piS
  snp_gen_out <- na.rm(snp_gen_out)
  snp_gen_out <- snp_gen_out[!is.infinite(snp_gen_out$NS),]
  merge(popnames, merge(data(gb_ncbi_fin), snp_gen_out, by.x="transcript", by.y="product"))
}