#HBPOP2022 Sig Diff Genes
#' analyzes individual genes for differences in genetic diversity
#' @param snp_gen_out dataframe generated by SNPGenie
#' @param gene character name of gene of interest (GB#)
#' @return dataframe
#' @import ggplot2
#' @importFrom stats t.test
#' @export

hbpop_snpsing <- function(snp_gen_out, gene) {
  snpgen <- snp_gen_out[which(snp_gen_out$GBold==gene),]
  snpgen_tt <- t.test(snpgen$NS~snpgen$Field1)
  snpgen_ttp <- snpgen_tt$p.value
  snpgen_plot <- ggplot(snpgen, aes(x=Field1, y=NS, fill=Field1)) + 
    geom_boxplot(outlier.color="black", notch=FALSE) + 
    labs(x="Management", y="NS") + theme_classic() + 
    theme(legend.position="none", 
      axis.title.x=element_text(color="black", size=12), axis.text.y=element_text(color="black", size=12)) + 
    ylab("piN/piS") + xlab("Management") + ggtitle(sprintf("%s", gene))
  out <- list(snpgen_tt, snpgen_ttp, snpgen_plot)
  return(out)
}


