---
title: "amelpool_supp"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{amelpool_supp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(amel.poolseq)
library(Imap)
```
# Genetic Diversity vs. Coverage

Depths output by samtools...include pre-trim variables.

```{r}
depth.samp <- read.csv("dp.csv", fill=T, header=T)
table3 <- merge(depth.samp, table.s.sd, by="Sample.Name")
x<-new.table2[,c('Field2', 'sample')]
names(table3)[1] <- 'sample'
y<-merge(x, table3, by = 'sample')
y<-y[!duplicated(y),]
dep.pi <- y

y <- lm(data=dep.pi, Mean_piS ~ Depth + Field2)
summary(y)
resid <- residuals(y)
dep.pi$resid <- resid
boxplot(dep.pi$resid~dep.pi$Field2)
abline(h=0)

depth.plot <- ggplot(dep.pi, aes(x=Depth, y=Mean_piS)) +
  geom_point(cex=3, pch=19) +
  geom_smooth(method='lm') + 
  ylab("Average piS") + xlab("Sequencing Depth") + ggtitle("Sequencing Depth vs. Average Genome-wide Genetic Diversity")
depth.plot
```

# Supplemental Table 1: FST by Geographic Distance
```{r}
library(geodist)
library(reshape2)

dist <- read.table("col_coord.tsv", header=T)
dist <- dist %>% filter(!row_number() %in% c(7,15,26,18,20,24)) %>% select(!index)

dist$ind <- c("LINF01F17", "LINF01F18", 'MALF01F17', 'MALF01F18', 'WINDF1F17', 'WINDF1F18', 'JULF1F18', 'BERF1F18', 'WYOF1F18', 'MEDF1F18', 'SAXF1F18', 'HAVF1F18', 'JULF1F17', 'LERF1F18', 'LINM1F18', 'WINDM1F18', 'BERM1F18', 'MALM1F18', 'LERM1F18', 'MEDM1F18', 'HAVM1F18', 'JULM1F19', 'WYOM1F18')

y <- geodist(dist, measure="geodesic")
list1 <- dist$ind
rownames(y) <- list1
colnames(y) <- list1
df5 <- melt(y, measure.vars=dput(as.character(colnames(y))))
df6 <- df5[!duplicated(apply(df5,1,function(x) paste(sort(x),collapse='_'))),]

pa_fst <- read.table("pa_fst_df", header=T)
mean.n0 <- data.frame(apply(pa_fst[6:ncol(pa_fst)],2,function(x) mean(x[x>0])))
mean.n0$samp <- rownames(mean.n0)
rownames(mean.n0) <- NULL
colnames(mean.n0) <- c("mean", "samp")
mean.n02 <- mean.n0 %>% mutate(
  Field1 = gsub('[.].*','', mean.n0$samp), 
  Field2 = gsub('.*[.]','', mean.n0$samp)
  ) %>% select(!(samp))

df <- df6 %>% inner_join(mean.n02, by=c('Var1'='Field1', 'Var2'='Field2')) 
df2 <- df6 %>% inner_join(mean.n02, by=c('Var1'='Field2', 'Var2'='Field1'))

df3 <- rbind(df, df2)
df3$Var3 <- paste(df3$Var1, df3$Var2, sep="_")

disfst <- ggplot(data=df3, aes(x=value, y=mean)) + geom_point(color='#000000', size=3, alpha=1) + ylab("Distance (m)") + xlab("Avg. Fst") + ggtitle("PA Fst vs. Distance")

```
